version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ghost
      POSTGRES_USER: ghost
      POSTGRES_PASSWORD: securepassword

  ghost:
    depends_on:
      - db
    image: ghost:5-alpine
    ports:
      - "8080:2368"
    restart: always
    environment:
      database__client: pg
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: securepassword
      database__connection__database: ghost
      url: http://localhost:8080

volumes:
  db_data: {}